export interface PlanetConfig {
  id:              string
  name:            string
  radius:          number
  scaleAU:         number
  color:           string
  emissive:        string
  roughness:       number
  metalness:       number
  rotationSpeed:   number
  diameter:        string
  mass:            string
  gravity:         string
  temperature:     string
  distanceFromSun: string
  orbitalPeriod:   string
  rotationPeriod:  string
  fact:            string
  description:     string   // ← tambah
}

export const PLANET_CONFIGS: Record<string, PlanetConfig> = {
  mercury: {
    id:              'mercury',
    name:            'Mercury',
    radius:          0.8,
    scaleAU:         28,
    color:           '#B5A9A0',
    emissive:        '#3A3330',
    roughness:       0.9,
    metalness:       0.1,
    rotationSpeed:   0.01,
    diameter:        '4,879 km',
    mass:            '3.30 × 10²³ kg',
    gravity:         '3.7 m/s²',
    temperature:     '167°C (avg)',
    distanceFromSun: '0.39 AU',
    orbitalPeriod:   '88 days',
    rotationPeriod:  '58.6 days',
    fact:            'Mercury has no atmosphere, causing extreme temperature swings from -180°C to 430°C.',
    description:     'Mercury is the smallest and innermost planet in the Solar System. Despite being closest to the Sun, it is not the hottest planet — that title belongs to Venus. Its heavily cratered surface resembles our Moon, shaped by billions of years of impacts.',
  },
  venus: {
    id:              'venus',
    name:            'Venus',
    radius:          1.9,
    scaleAU:         28,
    color:           '#E8C070',
    emissive:        '#4A3010',
    roughness:       0.8,
    metalness:       0.0,
    rotationSpeed:   0.004,
    diameter:        '12,104 km',
    mass:            '4.87 × 10²⁴ kg',
    gravity:         '8.87 m/s²',
    temperature:     '464°C',
    distanceFromSun: '0.72 AU',
    orbitalPeriod:   '225 days',
    rotationPeriod:  '243 days',
    fact:            'Venus rotates backwards compared to most planets, so the Sun rises in the west.',
    description:     'Venus is Earth\'s twin in size but a world of extremes. Its thick atmosphere of carbon dioxide traps heat in a runaway greenhouse effect, making it the hottest planet. Covered in volcanic plains and highland continents, Venus is shrouded in sulfuric acid clouds.',
  },
  earth: {
    id:              'earth',
    name:            'Earth',
    radius:          2.0,
    scaleAU:         28,
    color:           '#4A90D9',
    emissive:        '#0A2040',
    roughness:       0.7,
    metalness:       0.1,
    rotationSpeed:   0.05,
    diameter:        '12,742 km',
    mass:            '5.97 × 10²⁴ kg',
    gravity:         '9.81 m/s²',
    temperature:     '15°C (avg)',
    distanceFromSun: '1.00 AU',
    orbitalPeriod:   '365.25 days',
    rotationPeriod:  '24 hours',
    fact:            'Earth is the only known planet to harbor life, with liquid water covering 71% of its surface.',
    description:     'Earth is the third planet from the Sun and the only astronomical object known to harbor life. Its dynamic atmosphere, liquid water oceans, and magnetic field create the perfect conditions for life. Earth\'s axial tilt of 23.5° creates the seasons we experience throughout the year.',
  },
  mars: {
    id:              'mars',
    name:            'Mars',
    radius:          1.1,
    scaleAU:         28,
    color:           '#C1440E',
    emissive:        '#3A0E00',
    roughness:       0.95,
    metalness:       0.0,
    rotationSpeed:   0.048,
    diameter:        '6,779 km',
    mass:            '6.42 × 10²³ kg',
    gravity:         '3.72 m/s²',
    temperature:     '-60°C (avg)',
    distanceFromSun: '1.52 AU',
    orbitalPeriod:   '687 days',
    rotationPeriod:  '24.6 hours',
    fact:            'Mars hosts Olympus Mons, the tallest volcano in the solar system at 22 km high.',
    description:     'Mars, the Red Planet, is a cold desert world with the largest volcano and canyon system in the Solar System. Evidence suggests Mars once had liquid water on its surface. Today, rovers and landers continue to search for signs of ancient microbial life beneath its rusty soil.',
  },
  jupiter: {
    id:              'jupiter',
    name:            'Jupiter',
    radius:          5.5,
    scaleAU:         28,
    color:           '#C88B3A',
    emissive:        '#3A2010',
    roughness:       0.8,
    metalness:       0.0,
    rotationSpeed:   0.12,
    diameter:        '139,820 km',
    mass:            '1.90 × 10²⁷ kg',
    gravity:         '24.8 m/s²',
    temperature:     '-108°C',
    distanceFromSun: '5.20 AU',
    orbitalPeriod:   '11.9 years',
    rotationPeriod:  '9.9 hours',
    fact:            'Jupiter\'s Great Red Spot is a storm larger than Earth that has raged for over 350 years.',
    description:     'Jupiter is the largest planet in our Solar System — more than twice as massive as all other planets combined. This gas giant has no solid surface, just layers of swirling clouds of ammonia and water. Its powerful magnetic field and 95 known moons make it a mini solar system of its own.',
  },
  saturn: {
    id:              'saturn',
    name:            'Saturn',
    radius:          4.5,
    scaleAU:         28,
    color:           '#E4D090',
    emissive:        '#3A3010',
    roughness:       0.8,
    metalness:       0.0,
    rotationSpeed:   0.11,
    diameter:        '116,460 km',
    mass:            '5.68 × 10²⁶ kg',
    gravity:         '10.4 m/s²',
    temperature:     '-138°C',
    distanceFromSun: '9.54 AU',
    orbitalPeriod:   '29.5 years',
    rotationPeriod:  '10.7 hours',
    fact:            'Saturn is the least dense planet — it would float on water if you had an ocean big enough.',
    description:     'Saturn is the crown jewel of the Solar System, instantly recognizable by its stunning ring system made of ice and rock. This gas giant radiates more energy than it receives from the Sun. Its moon Titan has a thick atmosphere and liquid methane lakes, making it one of the most Earth-like worlds we know.',
  },
  uranus: {
    id:              'uranus',
    name:            'Uranus',
    radius:          3.2,
    scaleAU:         28,
    color:           '#7ECFC4',
    emissive:        '#0A2A28',
    roughness:       0.7,
    metalness:       0.1,
    rotationSpeed:   0.07,
    diameter:        '50,724 km',
    mass:            '8.68 × 10²⁵ kg',
    gravity:         '8.69 m/s²',
    temperature:     '-195°C',
    distanceFromSun: '19.2 AU',
    orbitalPeriod:   '84 years',
    rotationPeriod:  '17.2 hours',
    fact:            'Uranus rotates on its side with an axial tilt of 98°, likely from an ancient collision.',
    description:     'Uranus is an ice giant with a blue-green color from methane in its atmosphere. Unlike any other planet, it rotates on its side, meaning its poles experience 42 years of continuous sunlight followed by 42 years of darkness. It has 13 known rings and 28 moons.',
  },
  neptune: {
    id:              'neptune',
    name:            'Neptune',
    radius:          3.0,
    scaleAU:         28,
    color:           '#4060C8',
    emissive:        '#0A1040',
    roughness:       0.7,
    metalness:       0.1,
    rotationSpeed:   0.067,
    diameter:        '49,244 km',
    mass:            '1.02 × 10²⁶ kg',
    gravity:         '11.2 m/s²',
    temperature:     '-200°C',
    distanceFromSun: '30.1 AU',
    orbitalPeriod:   '165 years',
    rotationPeriod:  '16.1 hours',
    fact:            'Neptune has the fastest winds in the solar system, reaching 2,100 km/h.',
    description:     'Neptune is the farthest planet from the Sun and the windiest world in the Solar System. This deep blue ice giant was the first planet predicted mathematically before it was observed. Its largest moon Triton orbits backwards and is slowly spiraling inward, destined to break apart in about 3.6 billion years.',
  },
}

export const PLANET_IDS = Object.keys(PLANET_CONFIGS) as Array<keyof typeof PLANET_CONFIGS>